<a href="https://colab.research.google.com/github/akshaypt7/amazon_weekly_sales_viz/blob/main/Weekly_sales_amazon_project_(Nemora).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from google.colab import files
import pandas as pd
import io
import numpy as np
# !pip install voila
# !jupyter serverextension enable --sys-prefix voila

In [2]:

uploaded_file = files.upload()

Saving BusinessReport.csv to BusinessReport.csv

In [4]:
df = pd.read_csv(io.BytesIO(uploaded_file['BusinessReport.csv']))


try:

  df.drop([ 'Sessions',
        'Session Percentage', 'Page views', 'Page Views Percentage',
        'Featured Offer (Buy Box) Percentage', 'Total Order Items',
        'Unit Session Percentage','(Parent) ASIN'],axis=1,inplace= True)
  
except:
  pass

In [8]:
# Nemora

kattil = ['Decorative-Light-01','HY-LDOK-X8MQ']

light_kattil = ['NMP03-WY']

koodu = ['NMP02-DW','Decorative-Light-02','ZJ-JU30-M8TR','NMP02-DW-WB']

light_koodu = ['NMP02-WY-WB','NMP02-WY','NMP02-WD-WB']

pyramid = ['NMP14-WD-WB','NMP14-WD']

triangle = ['NMP10-RW']

lap_top_stand = ['NMFT07-WD']

head_set_stand = ['NMFT04-WD']


nemora_products = ['kattil','light_kattil','koodu','light_koodu','pyramid','triangle','lap_top_stand','head_set_stand']

In [12]:
df_kattil = pd.DataFrame()
df_light_kattil = pd.DataFrame()

df_koodu =pd.DataFrame()
df_light_koodu =pd.DataFrame()

df_pyramid =pd.DataFrame()

df_triangle= pd.DataFrame()

df_lap_top_stand= pd.DataFrame()

df_head_set_stand= pd.DataFrame()

In [13]:
for row in range(df.shape[0]):
  if df.iloc[row]['SKU'] in kattil:
    df_kattil = df_kattil.append(df.iloc[row])

  if df.iloc[row]['SKU'] in light_kattil:
    df_light_kattil = df_light_kattil.append(df.iloc[row])

  if df.iloc[row]['SKU'] in koodu:
    df_koodu = df_koodu.append(df.iloc[row])

  if df.iloc[row]['SKU'] in light_koodu:
    df_light_koodu = df_light_koodu.append(df.iloc[row])    

  if df.iloc[row]['SKU'] in pyramid:
    df_pyramid = df_pyramid.append(df.iloc[row]) 


  if df.iloc[row]['SKU'] in triangle:
    df_triangle = df_triangle.append(df.iloc[row]) 


  if df.iloc[row]['SKU'] in lap_top_stand:
    df_lap_top_stand = df_lap_top_stand.append(df.iloc[row]) 

  if df.iloc[row]['SKU'] in head_set_stand:
    df_head_set_stand = df_head_set_stand.append(df.iloc[row])

## Kattil

In [30]:
try:
  print(f'Total Units ordered : {df_kattil["Units Ordered"].sum()}')

except:
  print('No sales')
  
df_kattil

Total Units ordered : 2.0

,(Parent) ASIN,(Child) ASIN,Title,SKU,Units Ordered,Ordered Product Sales,Total Order Items
25,B08ZCP8DBS,B08ZCP8DBS,Nemora - Kerala Original Handmade Wooden Teak ...,Decorative-Light-01,2.0,"₹ 2,598.00",2.0

#### df_light_kattil

In [29]:
try:
  print(f'Total Units ordered : {df_light_kattil["Units Ordered"].sum()}')

except:
  print('No sales')
df_light_kattil

No sales

Empty DataFrame
Columns: []
Index: []

## Koodu

In [31]:
try:
  print(f'Total Units ordered : {df_koodu["Units Ordered"].sum()}')

except:
  print('No sales')

df_koodu

Total Units ordered : 20.0

,(Parent) ASIN,(Child) ASIN,Title,SKU,Units Ordered,Ordered Product Sales,Total Order Items
16,B097BRX6ZY,B097BRX6ZY,Nemora Decorative Pendant Light Without Bulb (...,NMP02-DW-WB,8.0,"₹ 10,382.09",8.0
17,B096FJG4FR,B096FJG4FR,Nemora - Kerala Original Handmade Wooden Teak ...,NMP02-DW,8.0,"₹ 10,992.00",6.0
21,B08ZDDJLMB,B08ZDDJLMB,Nemora - Kerala E27 Base 4 Watts Original Hand...,Decorative-Light-02,4.0,"₹ 5,596.00",3.0

#### Light Koodu

In [33]:
try:
  print(f'Total Units ordered : {df_light_koodu["Units Ordered"].sum()}')

except:
  print('No sales')

df_light_koodu

Total Units ordered : 4.0

,(Parent) ASIN,(Child) ASIN,Title,SKU,Units Ordered,Ordered Product Sales,Total Order Items
22,B097BRXTHF,B097BRXTHF,Nemora - Kerala Original Handmade E27 Base 4 W...,NMP02-WD-WB,3.0,"₹ 3,897.00",3.0
37,B097BRTV54,B097BRTV54,Nemora - Kerala Original Handmade Wooden Teak ...,NMP02-WY-WB,1.0,"₹ 1,299.00",1.0

## Pyramid

In [34]:
df_pyramid

Empty DataFrame
Columns: []
Index: []

## Traingle

In [35]:
df_triangle

Empty DataFrame
Columns: []
Index: []

## Lap_top_stand

In [36]:
df_lap_top_stand

,(Parent) ASIN,(Child) ASIN,Title,SKU,Units Ordered,Ordered Product Sales,Total Order Items
7,B09CMWSVTH,B09CMWSVTH,"Nemora Kerala Wooden Laptop Stand, Wooden Fini...",NMFT07-WD,44.0,"₹ 25,319.20",43.0

## Head_set_stand

In [37]:
df_head_set_stand

,(Parent) ASIN,(Child) ASIN,Title,SKU,Units Ordered,Ordered Product Sales,Total Order Items
38,B0987NY3WX,B0987NY3WX,"Nemora Kerala Wooden Teak Head Set Stand, Wood...",NMFT04-WD,1.0,₹ 445.58,1.0