In [90]:
from google.colab import files
import pandas as pd
import io
import numpy as np
!pip install voila
!jupyter serverextension enable --sys-prefix voila

Collecting voila
  Downloading voila-0.3.0-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 5.0 MB/s
Collecting websockets>=9.0
  Downloading websockets-10.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (111 kB)
     |████████████████████████████████| 111 kB 58.7 MB/s
Collecting nbconvert<7,>=6.0.0
  Downloading nbconvert-6.4.0-py3-none-any.whl (557 kB)
     |████████████████████████████████| 557 kB 52.2 MB/s
Requirement already satisfied: nbclient<0.6,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from voila) (0.5.9)
Collecting jupyter-client<8,>=6.1.3
  Downloading jupyter_client-7.1.0-py3-none-any.whl (129 kB)
     |████████████████████████████████| 129 kB 54.1 MB/s
Collecting jupyter-server<2.0.0,>=0.3.0
  Downloading jupyter_server-1.13.2-py3-none-any.whl (395 kB)
     |████████████████████████████████| 395 kB 70.2 MB/s
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8,>=6.1.3->voila) (4.9.1)
Requirement already satisfied: tornado>=4.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8,>=6.1.3->voila) (5.1.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8,>=6.1.3->voila) (0.3)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8,>=6.1.3->voila) (1.5.4)
Requirement already satisfied: traitlets in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8,>=6.1.3->voila) (5.1.1)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8,>=6.1.3->voila) (22.3.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8,>=6.1.3->voila) (2.8.2)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (21.3)
Collecting anyio<4,>=3.1.0
  Downloading anyio-3.5.0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 7.3 MB/s
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (1.8.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (0.2.0)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (21.3.0)
Collecting tornado>=4.1
  Downloading tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl (428 kB)
     |████████████████████████████████| 428 kB 58.6 MB/s
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (0.12.0)
Collecting websocket-client
  Downloading websocket_client-1.2.3-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 1.8 MB/s
Requirement already satisfied: nbformat in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (5.1.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from jupyter-server<2.0.0,>=0.3.0->voila) (2.11.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.7/dist-packages (from anyio<4,>=3.1.0->jupyter-server<2.0.0,>=0.3.0->voila) (2.10)
Collecting sniffio>=1.1
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from anyio<4,>=3.1.0->jupyter-server<2.0.0,>=0.3.0->voila) (3.10.0.2)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert<7,>=6.0.0->voila) (2.6.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert<7,>=6.0.0->voila) (4.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert<7,>=6.0.0->voila) (1.5.0)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.7/dist-packages (from nbconvert<7,>=6.0.0->voila) (0.1.2)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert<7,>=6.0.0->voila) (0.5.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert<7,>=6.0.0->voila) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert<7,>=6.0.0->voila) (0.8.4)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->jupyter-server<2.0.0,>=0.3.0->voila) (2.0.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat->jupyter-server<2.0.0,>=0.3.0->voila) (4.3.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<2.0.0,>=0.3.0->voila) (0.18.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<2.0.0,>=0.3.0->voila) (5.4.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<2.0.0,>=0.3.0->voila) (21.4.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<2.0.0,>=0.3.0->voila) (4.10.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<2.0.0,>=0.3.0->voila) (3.7.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->jupyter-client<8,>=6.1.3->voila) (1.15.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.7/dist-packages (from terminado>=0.8.3->jupyter-server<2.0.0,>=0.3.0->voila) (0.7.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.7/dist-packages (from argon2-cffi->jupyter-server<2.0.0,>=0.3.0->voila) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<2.0.0,>=0.3.0->voila) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<2.0.0,>=0.3.0->voila) (2.21)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert<7,>=6.0.0->voila) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->jupyter-server<2.0.0,>=0.3.0->voila) (3.0.6)
Installing collected packages: tornado, jupyter-client, sniffio, websocket-client, nbconvert, anyio, websockets, jupyter-server, voila
  Attempting uninstall: tornado
    Found existing installation: tornado 5.1.1
    Uninstalling tornado-5.1.1:
      Successfully uninstalled tornado-5.1.1
  Attempting uninstall: jupyter-client
    Found existing installation: jupyter-client 5.3.5
    Uninstalling jupyter-client-5.3.5:
      Successfully uninstalled jupyter-client-5.3.5
  Attempting uninstall: nbconvert
    Found existing installation: nbconvert 5.6.1
    Uninstalling nbconvert-5.6.1:
      Successfully uninstalled nbconvert-5.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires tornado~=5.1.0; python_version >= "3.0", but you have tornado 6.1 which is incompatible.
Successfully installed anyio-3.5.0 jupyter-client-7.1.0 jupyter-server-1.13.2 nbconvert-6.4.0 sniffio-1.2.0 tornado-6.1 voila-0.3.0 websocket-client-1.2.3 websockets-10.1

Enabling: voila
- Writing config: /usr/etc/jupyter
    - Validating...
Error loading server extension voila
      X is voila importable?

In [80]:
uploaded_file = files.upload()

Saving BusinessReport-09-01-22.csv to BusinessReport-09-01-22 (2).csv

In [81]:
df = pd.read_csv(io.BytesIO(uploaded_file['BusinessReport-09-01-22.csv']))


df.drop([ 'Sessions',
       'Session Percentage', 'Page views', 'Page Views Percentage',
       'Featured Offer (Buy Box) Percentage', 'Total Order Items',
       'Unit Session Percentage','(Parent) ASIN'],axis=1,inplace= True)

In [82]:

df.head()

  (Child) ASIN  ... Ordered Product Sales
0   B07TM3LRVB  ...          ₹ 388,170.00
1   B07TM3LRVB  ...          ₹ 217,920.00
2   B09GY4GGXX  ...           ₹ 13,727.96
3   B0849NLNTQ  ...           ₹ 62,297.04
4   B08332221J  ...           ₹ 44,929.43

[5 rows x 5 columns]

Our plann

We have to first get all the asins and then sort it into Purifit and its 5 products. 
Once that is done we can sum the total revenue and units. We get what we need. 

Now the first part is the difficult one, how are we going to do that. 

The things is there are 3 or more SKU of same product. Once we understand that what will we do? 

the thing is we have to add thier revenue and units. How do we do this. We can group by based on those asin values.

Lets just work on washing machine filter now.

In [83]:
washing_machine = ['5A-YB7Z-ZFXP','Washing_Machine_Filter','201']
washing_machine_cartridge = ['RW-0JGB-G59A','Washing_Machine_Cartridge']

shower_filter_10stage = ['New-103 A' , '104_Single', 'New-103_1', 'New-103', 'New-104']
shower_filter_10_stage_cartridge = ['103 C']


black_shower_filter = ['1Z-ZD5D-W1P5','ZF-FXQE-MFJY','New_901','901']
black_shower_filter_cartridge =['901_Cartidge']

zeus = ['PF3SPRY-01']
zeus_cartridge =['3SPRY-C']

shower_head = ['OK-H0DX-9N0N','109']
shower_head_cartridge = ['109_Cartridge']

alkaline_filter =['Alkaline-01']
alkaline_cartridge = ['105']


tap_filter = ['Tabs_p_06','Tabs_p_03','PFKTF-01']

In [84]:
df_wm = pd.DataFrame()
df_wm_cartridge = pd.DataFrame()

df_10stage =pd.DataFrame()
df_10stage_cartridge =pd.DataFrame()

df_black =pd.DataFrame()
df_black_cartridge =pd.DataFrame()

df_zeus= pd.DataFrame()
df_zeus_cartridge= pd.DataFrame()

df_shower_head= pd.DataFrame()
df_shower_head_cartridge= pd.DataFrame()

df_alkaline= pd.DataFrame()
df_alkaline_cartridge= pd.DataFrame()

df_tap_filter = pd.DataFrame()

In [85]:
# for i in Washing_machine:
for row in range(df.shape[0]):
  if df.iloc[row]['SKU'] in washing_machine:
    df_wm = df_wm.append(df.iloc[row])

  if df.iloc[row]['SKU'] in washing_machine_cartridge:
    df_wm_cartridge = df_wm_cartridge.append(df.iloc[row])  

  if df.iloc[row]['SKU'] in shower_filter_10stage:
    df_10stage = df_10stage.append(df.iloc[row])

  if df.iloc[row]['SKU'] in shower_filter_10_stage_cartridge:
    df_10stage_cartridge = df_10stage_cartridge.append(df.iloc[row])    


  if df.iloc[row]['SKU'] in black_shower_filter:
    df_black = df_black.append(df.iloc[row])

  if df.iloc[row]['SKU'] in black_shower_filter_cartridge:
    df_black_cartridge = df_black_cartridge.append(df.iloc[row])


  if df.iloc[row]['SKU'] in zeus:
    df_zeus = df_zeus.append(df.iloc[row])    


  if df.iloc[row]['SKU'] in zeus_cartridge:
    df_zeus_cartridge = df_zeus_cartridge.append(df.iloc[row])

  if df.iloc[row]['SKU'] in shower_head:
    df_shower_head = df_shower_head.append(df.iloc[row])

  if df.iloc[row]['SKU'] in shower_head_cartridge:
    df_shower_head_cartridge = df_shower_head_cartridge.append(df.iloc[row])


  if df.iloc[row]['SKU'] in alkaline_filter:
    df_alkaline = df_alkaline.append(df.iloc[row])

  if df.iloc[row]['SKU'] in alkaline_cartridge:
    df_alkaline_cartridge = df_alkaline_cartridge.append(df.iloc[row])

  if df.iloc[row]['SKU'] in tap_filter:
    df_tap_filter = df_tap_filter.append(df.iloc[row])

## Washing Machine Filter

In [86]:
df_wm

  (Child) ASIN  ... Units Ordered
0   B07TM3LRVB  ...         350.0
1   B07TM3LRVB  ...         200.0

[2 rows x 5 columns]

#### Washing Machine Cartridge

In [87]:
df_wm_cartridge

   (Child) ASIN  ... Units Ordered
18   B0859B5J8T  ...           9.0

[1 rows x 5 columns]

## 10 Stage Shower Filter

In [88]:
df_10stage

   (Child) ASIN  ... Units Ordered
5    B07KYFHTGF  ...          22.0
21   B07TJ1HDTM  ...           7.0
24   B0897LPBHR  ...           5.0
30   B07S8NC532  ...           2.0

[4 rows x 5 columns]

#### 10 stage Cartridge

In [89]:
df_10stage_cartridge

  (Child) ASIN  ... Units Ordered
9   B084JJWJ31  ...          22.0

[1 rows x 5 columns]

## Black Shower filter

In [70]:
df_black

   (Child) ASIN  ... Units Ordered
3    B0849NLNTQ  ...          39.0
10   B08976V1BZ  ...          16.0
42   B0849NLNTQ  ...           2.0

[3 rows x 5 columns]

#### Black Cartridge

In [71]:
df_black_cartridge

   (Child) ASIN  ... Units Ordered
12   B0858X26QM  ...          13.0

[1 rows x 5 columns]

## Zeus

In [72]:
df_zeus

   (Child) ASIN  ... Units Ordered
29   B09GXX6YN4  ...           3.0

[1 rows x 5 columns]

#### Zeus Cartridge

In [73]:
df_zeus_cartridge

Empty DataFrame
Columns: []
Index: []

## Shower Head

In [74]:
df_shower_head

  (Child) ASIN  ... Units Ordered
4   B08332221J  ...          34.0

[1 rows x 5 columns]

#### Shower Head Cartridge

In [75]:
df_shower_head_cartridge

  (Child) ASIN  ... Units Ordered
6   B0859193NJ  ...          24.0

[1 rows x 5 columns]

## Alkaline Water filter

In [76]:
df_alkaline

  (Child) ASIN  ... Units Ordered
7   B0957WJB9N  ...          19.0

[1 rows x 5 columns]

#### Alkaline Cartidge

In [77]:
df_alkaline_cartridge

   (Child) ASIN  ... Units Ordered
11   B09GF9JD9R  ...          15.0

[1 rows x 5 columns]

## Tap Filter

In [78]:
df_tap_filter

   (Child) ASIN  ... Units Ordered
2    B09GY4GGXX  ...          69.0
8    B09KRN87FH  ...          17.0
57   B09L64FT8X  ...           1.0

[3 rows x 5 columns]