<a href="https://colab.research.google.com/github/akshaypt7/amazon_weekly_sales_viz/blob/main/Weekly_sales_amazon_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
import io
import numpy as np
# !pip install voila
# !jupyter serverextension enable --sys-prefix voila

In [ ]:

uploaded_file = files.upload()

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded_file['BusinessReport.csv']))


try:

  df.drop([ 'Sessions',
        'Session Percentage', 'Page views', 'Page Views Percentage',
        'Featured Offer (Buy Box) Percentage', 'Total Order Items',
        'Unit Session Percentage','(Parent) ASIN'],axis=1,inplace= True)
  
except:
  pass

In [ ]:
washing_machine = ['5A-YB7Z-ZFXP','Washing_Machine_Filter','201']
washing_machine_cartridge = ['RW-0JGB-G59A','Washing_Machine_Cartridge']

shower_filter_10stage = ['New-103 A' , '104_Single', 'New-103_1', 'New-103', 'New-104']
shower_filter_10_stage_cartridge = ['103 C']


black_shower_filter = ['1Z-ZD5D-W1P5','ZF-FXQE-MFJY','New_901','901']
black_shower_filter_cartridge =['901_Cartidge']

zeus = ['PF3SPRY-01']
zeus_cartridge =['3SPRY-C']

shower_head = ['OK-H0DX-9N0N','109']
shower_head_cartridge = ['109_Cartridge']

alkaline_filter =['Alkaline-01']
alkaline_cartridge = ['105']


tap_filter = ['Tabs_p_06','Tabs_p_03','PFKTF-01']

In [ ]:
df_wm = pd.DataFrame()
df_wm_cartridge = pd.DataFrame()

df_10stage =pd.DataFrame()
df_10stage_cartridge =pd.DataFrame()

df_black =pd.DataFrame()
df_black_cartridge =pd.DataFrame()

df_zeus= pd.DataFrame()
df_zeus_cartridge= pd.DataFrame()

df_shower_head= pd.DataFrame()
df_shower_head_cartridge= pd.DataFrame()

df_alkaline= pd.DataFrame()
df_alkaline_cartridge= pd.DataFrame()

df_tap_filter = pd.DataFrame()

In [ ]:
# for i in Washing_machine:
for row in range(df.shape[0]):
  if df.iloc[row]['SKU'] in washing_machine:
    df_wm = df_wm.append(df.iloc[row])

  if df.iloc[row]['SKU'] in washing_machine_cartridge:
    df_wm_cartridge = df_wm_cartridge.append(df.iloc[row])  

  if df.iloc[row]['SKU'] in shower_filter_10stage:
    df_10stage = df_10stage.append(df.iloc[row])

  if df.iloc[row]['SKU'] in shower_filter_10_stage_cartridge:
    df_10stage_cartridge = df_10stage_cartridge.append(df.iloc[row])    


  if df.iloc[row]['SKU'] in black_shower_filter:
    df_black = df_black.append(df.iloc[row])

  if df.iloc[row]['SKU'] in black_shower_filter_cartridge:
    df_black_cartridge = df_black_cartridge.append(df.iloc[row])


  if df.iloc[row]['SKU'] in zeus:
    df_zeus = df_zeus.append(df.iloc[row])    


  if df.iloc[row]['SKU'] in zeus_cartridge:
    df_zeus_cartridge = df_zeus_cartridge.append(df.iloc[row])

  if df.iloc[row]['SKU'] in shower_head:
    df_shower_head = df_shower_head.append(df.iloc[row])

  if df.iloc[row]['SKU'] in shower_head_cartridge:
    df_shower_head_cartridge = df_shower_head_cartridge.append(df.iloc[row])


  if df.iloc[row]['SKU'] in alkaline_filter:
    df_alkaline = df_alkaline.append(df.iloc[row])

  if df.iloc[row]['SKU'] in alkaline_cartridge:
    df_alkaline_cartridge = df_alkaline_cartridge.append(df.iloc[row])

  if df.iloc[row]['SKU'] in tap_filter:
    df_tap_filter = df_tap_filter.append(df.iloc[row])

## Washing Machine Filter

In [ ]:
df_wm

  (Child) ASIN  ... Units Ordered
0   B07TM3LRVB  ...          60.0
1   B07TM3LRVB  ...          32.0

[2 rows x 5 columns]

#### Washing Machine Cartridge

In [ ]:
df_wm_cartridge

   (Child) ASIN  ... Units Ordered
10   B0859B5J8T  ...           2.0

[1 rows x 5 columns]

## 10 Stage Shower Filter

In [ ]:
df_10stage

   (Child) ASIN  ... Units Ordered
8    B07KYFHTGF  ...           2.0
21   B0897LPBHR  ...           2.0

[2 rows x 5 columns]

#### 10 stage Cartridge

In [ ]:
df_10stage_cartridge

Empty DataFrame
Columns: []
Index: []

## Black Shower filter

In [ ]:
df_black

   (Child) ASIN  ... Units Ordered
3    B0849NLNTQ  ...           7.0
11   B08976V1BZ  ...           2.0
20   B0849NLNTQ  ...           2.0

[3 rows x 5 columns]

#### Black Cartridge

In [ ]:
df_black_cartridge

  (Child) ASIN  ... Units Ordered
9   B0858X26QM  ...           3.0

[1 rows x 5 columns]

## Zeus

In [ ]:
df_zeus

Empty DataFrame
Columns: []
Index: []

#### Zeus Cartridge

In [ ]:
df_zeus_cartridge

Empty DataFrame
Columns: []
Index: []

## Shower Head

In [ ]:
df_shower_head

  (Child) ASIN  ... Units Ordered
2   B08332221J  ...           8.0

[1 rows x 5 columns]

#### Shower Head Cartridge

In [ ]:
df_shower_head_cartridge

  (Child) ASIN  ... Units Ordered
5   B0859193NJ  ...           5.0

[1 rows x 5 columns]

## Alkaline Water filter

In [ ]:
df_alkaline

   (Child) ASIN  ... Units Ordered
14   B0957WJB9N  ...           2.0

[1 rows x 5 columns]

#### Alkaline Cartidge

In [ ]:
df_alkaline_cartridge

   (Child) ASIN  ... Units Ordered
17   B09GF9JD9R  ...           2.0

[1 rows x 5 columns]

## Tap Filter

In [ ]:
df_tap_filter

   (Child) ASIN  ... Units Ordered
4    B09GY4GGXX  ...           6.0
7    B09KRN87FH  ...           3.0
29   B09L64FT8X  ...           1.0

[3 rows x 5 columns]